"""create_memory_profile_tables

Revision ID: 797fd0d5e59a
Revises: f0a1b2c3d4e5
Create Date: 2026-06-01 08:32:21.419539+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '797fd0d5e59a'
down_revision: Union[str, None] = 'f0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_key', sa.String(length=128), nullable=False),
    sa.Column('slot_type', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_slots_slot_key'), 'memory_slots', ['slot_key'], unique=True)
    op.create_index(op.f('ix_memory_slots_slot_type'), 'memory_slots', ['slot_type'], unique=False)
    op.create_table('memory_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('candidate_text', sa.Text(), nullable=False),
    sa.Column('suggested_slot_key', sa.String(length=128), nullable=True),
    sa.Column('suggested_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=True),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_hash', name='uq_user_candidate')
    )
    op.create_index(op.f('ix_memory_candidates_user_id'), 'memory_candidates', ['user_id'], unique=False)
    op.create_table('user_memory_slot_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('slot_value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['slot_id'], ['memory_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_id', name='uq_user_memory_slot')
    )
    op.create_index(op.f('ix_user_memory_slot_values_slot_id'), 'user_memory_slot_values', ['slot_id'], unique=False)
    op.create_index(op.f('ix_user_memory_slot_values_user_id'), 'user_memory_slot_values', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memory_slot_values_user_id'), table_name='user_memory_slot_values')
    op.drop_index(op.f('ix_user_memory_slot_values_slot_id'), table_name='user_memory_slot_values')
    op.drop_table('user_memory_slot_values')
    op.drop_index(op.f('ix_memory_candidates_user_id'), table_name='memory_candidates')
    op.drop_table('memory_candidates')
    op.drop_index(op.f('ix_memory_slots_slot_type'), table_name='memory_slots')
    op.drop_index(op.f('ix_memory_slots_slot_key'), table_name='memory_slots')
    op.drop_table('memory_slots')
    # ### end Alembic commands ###
