"""init schema

Revision ID: 9b5e75d9db39
Revises: 
Create Date: 2026-05-13 17:09:23.970555+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b5e75d9db39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True, comment='Celery 任务 ID'),
    sa.Column('type', sa.Enum('DOCUMENT_PROCESS', 'BATCH_EMBEDDING', 'SUMMARY_GENERATE', name='task_type_enum'), nullable=False, comment='任务类型'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='task_status_enum'), nullable=False, comment='任务状态'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='关联业务对象 ID'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度百分比 0-100'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='任务结束时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_records_celery_task_id'), 'task_records', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_task_records_related_id'), 'task_records', ['related_id'], unique=False)
    op.create_index(op.f('ix_task_records_status'), 'task_records', ['status'], unique=False)
    op.create_index(op.f('ix_task_records_type'), 'task_records', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名（唯一）'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt 哈希后的密码'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), nullable=False, comment='用户角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('chunk_strategy', sa.Enum('RECURSIVE', 'MARKDOWN_HEADER', name='chunk_strategy_enum'), nullable=False, comment='分块策略'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分块大小（字符数）'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='分块重叠（字符数）'),
    sa.Column('collection_name', sa.String(length=128), nullable=True, comment='向量库 Collection 名称'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name')
    )
    op.create_index(op.f('ix_knowledge_bases_created_by'), 'knowledge_bases', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_table('mcp_server_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='MCP Server 显示名（唯一）'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述用途'),
    sa.Column('transport_type', sa.Enum('STDIO', 'SSE', 'HTTP', name='mcp_transport_enum'), nullable=False, comment='传输协议类型'),
    sa.Column('connection_uri', sa.String(length=512), nullable=False, comment='连接命令或 URL'),
    sa.Column('env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='启动环境变量（JSON）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_server_configs_created_by'), 'mcp_server_configs', ['created_by'], unique=False)
    op.create_index(op.f('ix_mcp_server_configs_name'), 'mcp_server_configs', ['name'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题（通常取首条消息前几十字）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='LLM 压缩的对话摘要'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('kb_id', sa.Integer(), nullable=True, comment='关联的知识库 ID（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_kb_id'), 'chat_sessions', ['kb_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=32), nullable=False, comment='文件类型（pdf/docx/md/txt 等）'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='服务器存储路径'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='分块数量（处理完成后填充）'),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'CHUNKING', 'EMBEDDING', 'COMPLETED', 'FAILED', name='document_status_enum'), nullable=False, comment='文档处理状态'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('kb_id', sa.Integer(), nullable=False, comment='所属知识库 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role_enum'), nullable=False, comment='消息角色'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息正文'),
    sa.Column('agent_source', sa.Enum('USER', 'ROUTER', 'RAG', 'TOOL', 'SUMMARY', name='agent_source_enum'), nullable=True, comment='产出该消息的 Agent 来源'),
    sa.Column('tool_calls_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用详情（JSON）'),
    sa.Column('token_usage', sa.Integer(), nullable=True, comment='Token 消耗数'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_kb_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_mcp_server_configs_name'), table_name='mcp_server_configs')
    op.drop_index(op.f('ix_mcp_server_configs_created_by'), table_name='mcp_server_configs')
    op.drop_table('mcp_server_configs')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_created_by'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_records_type'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_status'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_related_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_celery_task_id'), table_name='task_records')
    op.drop_table('task_records')
    # ### end Alembic commands ###
