"""add_kb_id_to_memory_facts

Revision ID: 500d84ac8fa8
Revises: b7ca32917315
Create Date: 2026-05-20 13:03:37.624763+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500d84ac8fa8'
down_revision: Union[str, None] = 'b7ca32917315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_facts', sa.Column('kb_id', sa.Integer(), nullable=True, comment='关联知识库 ID（NULL 为全局记忆）'))
    op.create_index(op.f('ix_memory_facts_kb_id'), 'memory_facts', ['kb_id'], unique=False)
    op.create_foreign_key(None, 'memory_facts', 'knowledge_bases', ['kb_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memory_facts', type_='foreignkey')
    op.drop_index(op.f('ix_memory_facts_kb_id'), table_name='memory_facts')
    op.drop_column('memory_facts', 'kb_id')
    # ### end Alembic commands ###
