"""create_memory_facts

Revision ID: b7ca32917315
Revises: a3f1c2d4e5b6
Create Date: 2026-05-20 10:13:55.532594+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ca32917315'
down_revision: Union[str, None] = 'a3f1c2d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='来源会话 ID（可选）'),
    sa.Column('fact_type', sa.Enum('ERROR_LESSON', 'ENV_CONSTRAINT', 'PREFERENCE', 'KNOWLEDGE', name='memory_fact_type_enum'), nullable=False, comment='记忆事实类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆事实文本内容'),
    sa.Column('importance', sa.Float(), nullable=False, comment='重要性评分（0.0 ~ 1.0）'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='被检索并采用的次数'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次被检索访问时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_facts_session_id'), 'memory_facts', ['session_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_user_id'), 'memory_facts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_facts_user_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_session_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    # ### end Alembic commands ###
